spring:
  application:
    name: dugoga
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  token:
    expiration:
      access-token: 1800000 # 30 minutes
      refresh-token: 1209600000 # 14 days