spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dugoga
    username: dugoga
    password: dugoga

  data:
    redis:
      host: localhost
      port: 6379
      cache-access-token: accessToken
      cache-refresh-token: refreshToken
      default-ttl-sec: 86400