spring:
  application:
    name: dugoga
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  token:
    expiration:
      access-token: ${JWT_ACCESS_TOKEN_EXPIRATION}
      refresh-token: ${JWT_REFRESH_TOKEN_EXPIRATION}